### PR TITLE
Check if exception stack trace is null

### PR DESCRIPTION
**Pull request by Ivan-L**
This pull request adds null checks to any references to the Exception.StackTrace property prior to using it because in some instances, the StackTrace property may be null. Before these null checks, both Android and iOS would crash when recording such exceptions.

Issues addressed: #32 and #38

### CODE REVIEW

**Comment by chrissingh** [comment]
See updates were applied for null check on Android for version 1.2 on Nuget, but bug still exists on iOS.

**Comment by Ivan-L** [comment]
Yeah it seems that the code was updated separately from this pull request. I will update this pull request and request that it be merged again.

**Comment by Ivan-L** [comment]
@drungrin @chrissingh, the PR has been updated. Please note that this PR resolves the null check issue on both iOS and Android, including the case where the stack trace is split using a Regex on both platforms. Please would you have a look at the changes?

**Comment by chrissingh** [comment]
Thanks Ivan, changes look good. @drungrin  Any time frame on releasing via Nuget?

**Comment by Ivan-L** [comment]
Yeah I was going to ask the same. @drungrin - Do you first wait for a sufficient amount of changes to accumulate before a new release via NuGet? The app I am working on would benefit from the fixes in this PR.

**Comment by drungrin** [comment]
No, I just release when needed, but I need a spare time to do that. Not found any yet.

**Comment by drungrin** [comment]
Released 1.3 on nuget.org

**Comment by chrissingh** [comment]
@drungrin  Thanks a lot.

**Comment by Ivan-L** [comment]
Thank you @drungrin.

**Comment by Ivan-L** [comment]
@drungrin - was the latest code from master included in the 1.3 release? I upgraded the Fabric, Crashlytics and Answers NuGet packages to version 1.3, decompiled CrashlyticsKit.Platform on iOS using Visual Studio for Mac and do not see the changes to CrashlyticsKit.Initializer.RecordManagedException. The app is still crashing when certain exceptions where the StackTrace is null are being recorded.

**Comment by drungrin** [comment]
Checked and it wasn't included. MB.

Published 1.4. Sorry about that.

**Pull request merged**
